MAPEAMENTO = {
    "codigo": [
        "codigo do produto",
        "código do produto",
        "codigo",
        "código",
        "sku",
        "id",
        "cod produto",
        "cod_produto",
        "referencia",
        "referência",
        "ref",
    ],
    "gtin": [
        "gtin",
        "ean",
        "codigo de barras",
        "código de barras",
        "gtin/ean",
        "barcode",
    ],
    "produto": [
        "descricao",
        "descrição",
        "nome",
        "produto",
        "titulo",
        "title",
    ],
    "preco": [
        "preco",
        "preço",
        "valor",
        "price",
    ],
    "descricao_curta": [
        "descricao curta",
        "descrição curta",
        "resumo",
    ],
    "descricao_complementar": [
        "descricao complementar",
        "descrição complementar",
        "descricao longa",
        "descrição longa",
        "descricao completa",
        "descrição completa",
        "observacoes produto",
        "observações produto",
    ],
    "imagem": [
        "url imagens externas",
        "url imagem",
        "url_imagem",
        "url imagens",
        "imagem",
        "image",
        "foto",
    ],
    "link": [
        "link externo",
        "url produto",
        "produto url",
        "link produto",
        "link",
        "url",
        "site",
    ],
    "marca": [
        "marca",
        "brand",
    ],
    "estoque": [
        "estoque",
        "quantidade",
        "qtd",
        "stock",
        "saldo",
        "balanco",
        "balanço",
    ],
    "ncm": [
        "ncm",
    ],
    "origem": [
        "origem",
    ],
    "peso_liquido": [
        "peso liquido",
        "peso líquido",
    ],
    "peso_bruto": [
        "peso bruto",
    ],
    "estoque_minimo": [
        "estoque minimo",
        "estoque mínimo",
    ],
    "estoque_maximo": [
        "estoque maximo",
        "estoque máximo",
    ],
    "unidade": [
        "unidade",
        "un",
    ],
    "tipo": [
        "tipo",
    ],
    "situacao": [
        "situacao",
        "situação",
        "status",
    ],
    "preco_custo": [
        "preco de custo",
        "preço de custo",
        "custo",
        "cost",
    ],
}
