MAPEAMENTO = {
    "codigo": [
        "codigo",
        "código",
        "codigo do produto",
        "código do produto",
        "sku",
        "id",
        "cod produto",
        "cod_produto",
        "referencia",
        "referência",
        "ref",
    ],
    "produto": [
        "produto",
        "nome",
        "descricao",
        "descrição",
        "titulo",
        "title",
    ],
    "preco": [
        "preco",
        "preço",
        "valor",
        "price",
    ],
    "descricao_curta": [
        "descricao curta",
        "descrição curta",
        "resumo",
        "descricao curta do produto",
        "descrição curta do produto",
    ],
    "imagem": [
        "imagem",
        "image",
        "url imagem",
        "url_imagem",
        "url imagens",
        "foto",
    ],
    "link": [
        "link",
        "url",
        "produto url",
        "link produto",
        "link externo",
    ],
    "marca": [
        "marca",
        "brand",
    ],
    "estoque": [
        "estoque",
        "quantidade",
        "qtd",
        "stock",
        "saldo",
        "balanco",
        "balanço",
    ],
}
