# -*- coding: utf-8 -*-
from __future__ import annotations

import os
from typing import Dict, List, Set

DEFAULT_PROFILE_DIR = os.path.join("data", "mapeamentos")

BLING_CADASTRO_FIELDS: List[str] = [
    "codigo",
    "descricao",
    "descricao curta",
    "descricao complementar",
    "marca",
    "categoria",
    "unidade",
    "preco",
    "preco promocional",
    "custo",
    "ncm",
    "origem",
    "gtin",
    "gtin embalagem",
    "peso liquido (kg)",
    "peso bruto (kg)",
    "largura (cm)",
    "altura (cm)",
    "profundidade (cm)",
    "estoque minimo",
    "estoque maximo",
    "estoque atual",
    "localizacao",
    "fornecedor",
    "codigo fornecedor",
    "slug",
    "url video",
    "imagem 1",
    "imagem 2",
    "imagem 3",
    "imagem 4",
    "imagem 5",
    "observacoes",
]

BLING_ESTOQUE_FIELDS: List[str] = [
    "codigo",
    "descricao",
    "deposito",
    "saldo",
    "saldo virtual",
    "estoque minimo",
    "estoque maximo",
    "localizacao",
]

REQUIRED_FIELDS_CADASTRO: List[str] = [
    "codigo",
    "descricao curta",
]

REQUIRED_FIELDS_ESTOQUE: List[str] = [
    "codigo",
    "deposito",
    "saldo",
]

FIELD_SYNONYMS: Dict[str, List[str]] = {
    "codigo": [
        "codigo",
        "cod",
        "sku",
        "referencia",
        "ref",
        "cod produto",
        "codigo produto",
        "id produto",
        "part number",
        "pn",
        "codigo interno",
        "codigo pai",
    ],
    "descricao": [
        "descricao",
        "descrição",
        "nome",
        "produto",
        "nome produto",
        "titulo",
        "title",
    ],
    "descricao curta": [
        "descricao curta",
        "descrição curta",
        "descricao do produto",
        "descrição do produto",
        "nome",
        "titulo",
        "title",
        "produto",
        "nome produto",
    ],
    "descricao complementar": [
        "descricao complementar",
        "descrição complementar",
        "descricao longa",
        "descrição longa",
        "texto longo",
        "detalhes",
        "informacoes",
        "informações",
    ],
    "marca": [
        "marca",
        "brand",
        "fabricante",
    ],
    "categoria": [
        "categoria",
        "departamento",
        "grupo",
        "tipo",
        "segmento",
        "colecao",
        "coleção",
    ],
    "unidade": [
        "unidade",
        "und",
        "un",
        "unit",
    ],
    "preco": [
        "preco",
        "preço",
        "valor",
        "valor venda",
        "preco venda",
        "preço venda",
        "venda",
        "price",
    ],
    "preco promocional": [
        "preco promocional",
        "preço promocional",
        "preco promo",
        "preço promo",
        "promocional",
        "promo",
        "sale price",
    ],
    "custo": [
        "custo",
        "valor custo",
        "preco custo",
        "preço custo",
        "cost",
    ],
    "ncm": [
        "ncm",
        "classificacao fiscal",
        "classificação fiscal",
    ],
    "origem": [
        "origem",
        "origem mercadoria",
    ],
    "gtin": [
        "gtin",
        "ean",
        "ean13",
        "codigo de barras",
        "código de barras",
        "barcode",
        "gtin/ean",
    ],
    "gtin embalagem": [
        "gtin embalagem",
        "ean embalagem",
        "codigo barras embalagem",
        "código barras embalagem",
        "barcode embalagem",
    ],
    "peso liquido (kg)": [
        "peso liquido",
        "peso líquido",
        "peso",
        "peso liq",
        "peso liquido kg",
        "peso líquido kg",
    ],
    "peso bruto (kg)": [
        "peso bruto",
        "peso bruto kg",
    ],
    "largura (cm)": [
        "largura",
        "width",
        "largura cm",
    ],
    "altura (cm)": [
        "altura",
        "height",
        "altura cm",
    ],
    "profundidade (cm)": [
        "profundidade",
        "comprimento",
        "length",
        "depth",
        "profundidade cm",
        "comprimento cm",
    ],
    "estoque minimo": [
        "estoque minimo",
        "estoque mínimo",
        "minimo",
        "mínimo",
        "estoque min",
        "estoque mínimo ideal",
    ],
    "estoque maximo": [
        "estoque maximo",
        "estoque máximo",
        "maximo",
        "máximo",
        "estoque max",
    ],
    "estoque atual": [
        "estoque",
        "quantidade",
        "qtd",
        "saldo",
        "estoque atual",
        "qtde",
        "quant",
        "disponivel",
        "disponível",
    ],
    "saldo": [
        "saldo",
        "estoque",
        "quantidade",
        "qtd",
        "qtde",
        "saldo atual",
        "estoque atual",
    ],
    "saldo virtual": [
        "saldo virtual",
        "estoque virtual",
        "virtual",
    ],
    "deposito": [
        "deposito",
        "depósito",
        "deposito id",
        "depósito id",
        "id deposito",
        "id depósito",
        "warehouse",
    ],
    "localizacao": [
        "localizacao",
        "localização",
        "rua",
        "prateleira",
        "endereco estoque",
        "posição",
        "posicao",
    ],
    "fornecedor": [
        "fornecedor",
        "supplier",
        "fabricante",
        "distribuidor",
    ],
    "codigo fornecedor": [
        "codigo fornecedor",
        "código fornecedor",
        "ref fornecedor",
        "referencia fornecedor",
        "sku fornecedor",
        "codigo do fornecedor",
    ],
    "slug": [
        "slug",
        "url amigavel",
        "url amigável",
        "handle",
    ],
    "url video": [
        "video",
        "vídeo",
        "url video",
        "url vídeo",
        "youtube",
        "link video",
        "link vídeo",
    ],
    "imagem 1": [
        "imagem",
        "img",
        "foto",
        "image",
        "imagem 1",
        "foto 1",
        "link imagem",
        "url imagem",
        "imagem principal",
    ],
    "imagem 2": [
        "imagem 2",
        "foto 2",
        "img 2",
        "image 2",
    ],
    "imagem 3": [
        "imagem 3",
        "foto 3",
        "img 3",
        "image 3",
    ],
    "imagem 4": [
        "imagem 4",
        "foto 4",
        "img 4",
        "image 4",
    ],
    "imagem 5": [
        "imagem 5",
        "foto 5",
        "img 5",
        "image 5",
    ],
    "observacoes": [
        "observacoes",
        "observações",
        "obs",
        "comentario",
        "comentário",
        "notas",
    ],
}

MULTI_SOURCE_ALLOWED_FIELDS: Set[str] = {
    "imagem 1",
    "imagem 2",
    "imagem 3",
    "imagem 4",
    "imagem 5",
}

IMAGE_KEYWORDS: Set[str] = {
    "imagem",
    "img",
    "foto",
    "image",
    "images",
    "fotos",
    "url imagem",
    "link imagem",
}
